spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/wextransactions
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
management:
  endpoints:
    web:
      exposure:
        include: '*'
api:
  fiscaldata:
    base: https://api.fiscaldata.treasury.gov/services/api/fiscal_service
